language: objective-c
osx_image: xcode9.2
before_install:
  - brew update
  - brew install cookiecutter
  - brew install git-flow
  - brew install swiftgen
  - brew upgrade carthage
script:
  - cookiecutter --no-input gh:artemnovichkov/swift-project-template
  - xcodebuild clean build -project Project/Project.xcodeproj CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO